FEATURE: Separate sidebar links for anniv and bday
discourse/discourse-cakeday pull request #85
Opened 2022-10-12 21:28 UTC by oblakeerickson

Instead of a single link titled "Cakeday" there will now be two links
added to the sidebar: "Anniversary" and "Birthday".

2022-10-12 21:46 UTC, keegangeorge approved these changes
Approved, but two minor changes mentioned in comments before merging

2022-10-12 21:46 UTC, keegangeorge commented on assets/javascripts/discourse/initializers/cakeday.js
> +        let route = "cakeday.anniversaries.today";
I think we no longer need `let` here. Could we use `const` instead **or** simply inline it:
```javascript
return {
   route: "cakeday.anniversaries.today",
   label: "anniversaries.title",
   className: "cakeday-link",
 };
```

2022-10-12 21:46 UTC, keegangeorge commented on assets/javascripts/discourse/initializers/cakeday.js
> +        return {
Same as above comment

2022-10-13 01:43 UTC, pmusaraj requested changes
Actually, I'm surprised this even works for sidebar. I guess we've added backwards-compatibility to sidebar for `api.decorateWidget`, is that correct @tgxworld? 

We should add a test and we should use `api.addCommunitySectionLink`, despite it being marked as "experimental", it's the correct way forward for most things sidebar.

2022-10-13 01:43 UTC, pmusaraj commented on assets/javascripts/discourse/initializers/cakeday.js
> +          "cakeday.anniversaries.today",
This doesn't look right, and test failures seem relevant. This needs to be `route: "cakeday.anniversaries.today"`, I believe?

2022-10-13 01:55 UTC, oblakeerickson commented
Ya I agree. I found that api and got it working locally. Just wanted to
test it out with the sidebar plug-in first.

And ya I can work on adding a test too.

On Wed, Oct 12, 2022 at 7:44 PM Penar Musaraj ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Actually, I'm surprised this even works for sidebar. I guess we've added
> backwards-compatibility to sidebar for api.decorateWidget, is that
> correct @tgxworld <https://github.com/tgxworld>?
>
> We should add a test and we should use api.addCommunitySectionLink,
> despite it being marked as "experimental", it's the correct way forward for
> most things sidebar.
> ------------------------------
>
> In assets/javascripts/discourse/initializers/cakeday.js
> <https://github.com/discourse/discourse-cakeday/pull/85#discussion_r994032085>
> :
>
> > @@ -155,21 +155,27 @@ function initializeCakeday(api) {
>        }
>      });
>
> -    api.decorateWidget("hamburger-menu:generalLinks", () => {
> -      let route;
> +    if (cakedayEnabled) {
> +      api.decorateWidget("hamburger-menu:generalLinks", () => {
> +
> +        return {
> +          "cakeday.anniversaries.today",
>
> This doesn't look right, and test failures seem relevant. This needs to be route:
> "cakeday.anniversaries.today", I believe?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/discourse/discourse-cakeday/pull/85#pullrequestreview-1139908056>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALL4QCJJCBSPOVQC3PS3ILWC5SODANCNFSM6AAAAAARDVSV7E>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-13 18:38 UTC, pmusaraj approved these changes
Looks good!

2022-10-13 18:39 UTC, merged